import Head from "next/head";
import Hello from "@domains/Hello.tsx";
import { css } from "@emotion/react";
import Button from "@components/atoms/button";
import FloatingButton from "@components/atoms/floatingButton";

export default function Home() {
  return (
    <div
      css={css`
        height: 100vh;
        width: 100vw;
        display: flex;
        flex-direction: column;
      `}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hello />
      <Button
        variant="outlined"
        backgroundColor="#D4AA71"
        css={css`
          width: 295px;
        `}
      >
        button
      </Button>
      <FloatingButton
        css={css`
          position: absolute;
          bottom: 60px;
          right: 16px;
          z-index: 2;
        `}
      >
        button
      </FloatingButton>
    </div>
  );
}
