- name: Checkout target branch
  uses: actions/checkout@v3
  with:
    ref: release

- name: Checkout target branch
  run: git checkout main

- name: Checkout target branch
  run: git checkout release

- name: Configuration Github Profile
  run: |
    git config --global user.email ${{ secrets.MYEMAIL }}
    git config --global user.name ${{ secrets.MYNAME }}

- name: Merge source branch
  run: git merge  -Xtheirs main --allow-unrelated-histories

- name: Push source branch
  run: git push origin release
